name: customdrl
channels:
  - defaults
dependencies:
  - pip
  - python=3
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - traitlets
  - ipython_genutils
  - jupyter
  - pandas
  - matplotlib
  - seaborn
